---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-07-22 - 06:52:32 +0000
  labels:
    app.kubernetes.io/name: todo
    app.kubernetes.io/version: v1
  name: todo
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo
        app.kubernetes.io/version: v1
    spec:
      containers:
        - image: quay.io/kahlai/todo:v1
          name: todo
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
          volumeMounts: 
            - name: todo-config
              mountPath: "/work/config/"
              readOnly: true
      volumes:
        - name: todo-config
          configMap:
            name: todo-config
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: config-autoscaler
 namespace: knative-serving
data:
 scale-to-zero-grace-period: "10s"
